
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
sources:
  - name: gz_raw_data as raw
    tables: 
      - name: sales
        identifier: raw_gz_sales 
      - name: product
        identifier: raw_gz_product 
      - name: ship
        identifier: raw_gz_ship 

